// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TestGen from "./Test.gen";

function add(a, b) {
  return a + b | 0;
}

function divide(prim0, prim1) {
  return TestGen.divide(prim0, prim1);
}

var b = TestGen.divide(10, 3);

export {
  add ,
  divide ,
  b ,
  
}
/* b Not a pure module */
